Repository googleapis/python-appengine-admin, pull requests merged in 2021-04, with the labels that each got.

#2 chore: add constraints file
  setup.py
  testing/constraints-3.10.txt
  testing/constraints-3.11.txt
  testing/constraints-3.6.txt
  testing/constraints-3.7.txt
  testing/constraints-3.8.txt
  testing/constraints-3.9.txt
Labels: automerge, cla: yes

#5 chore: track generated files
  .pre-commit-config.yaml
  docs/appengine_admin_v1/types.rst
  google/cloud/appengine_admin_v1/__init__.py
  synth.metadata
Labels: api: appengine, automerge, cla: yes

#8 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  google/cloud/appengine_admin_v1/__init__.py
  renovate.json
  synth.metadata
Labels: api: appengine, automerge, cla: yes, context: partial

#10 chore: prevent normalization of semver versioning
  setup.py
Labels: api: appengine, cla: yes

#12 chore(revert): revert preventing normalization
  setup.py
Labels: api: appengine, cla: yes
